### PR TITLE
If replacing the input’s content via paste, select all after titleizing

### PR DESCRIPTION
**Pull request by j-f1**
This allows the user to paste something into the input, then copy it directly out again without having to manually select the result.

### CODE REVIEW

**Comment by j-f1** [comment]
Looks like I’m getting a 403 on [the deployment URL](https://zeit.co/zeit/title-site/yuqnmcpkqj?redirect=1&gh=1). Would it be possible to make those public?

**Comment by j-f1** [comment]
Friendly ping @leo :)

**Comment by j-f1** [comment]
Fixed a bug ⬆️

**Comment by Kikobeats** [comment]
c'mon @leo  this is awesome

**Comment by rauchg** [comment]
It seems nothing is resetting `replacingWithPaste` back to `false`?

**Comment by j-f1** [comment]
@rauchg it’s reset in `handleChange`.

**Comment by rauchg** [comment]
Nice. Thanks

**Pull request merged**
