### PR TITLE
Add dark mode support

### PR DESCRIPTION
**Pull request by lachlanjc**
(Merge #14 first)

Screen Shot 2020-01-08 at 1 09 05 AM

Live preview: https://title-git-dark.lachlanjc.now.sh

### CODE REVIEW

**Comment by j-f1** [comment]
I was going to suggest you get rid of the custom background color since Safari will automatically switch the text and background colors in dark mode, but Chrome doesn’t support `supported-color-schemes` or its successor `color-scheme` :(

Could you change the dark background to `#1E1E1E` to match the native dark mode?

**Comment by lachlanjc** [comment]
@j-f1 Indeed. Do you mean the input or the page background?

**Comment by j-f1** [comment]
Both

**Comment by lachlanjc** [comment]
Sure @j-f1, done!

**Review by j-f1 — APPROVED** [review]

**Comment by leerob** [comment]
@lachlanjc You're the best 🙏

**Comment by leerob** [comment]
Replaced by https://github.com/vercel/title-site/pull/28.

**Pull request closed without merging**
